import * as Yup from 'yup';


export const AllSchema = Yup.object().shape({
  // General
  seller_id: Yup.string().nullable().required('General: Seller ID is required'),
  seller_price: Yup.number('General: Should be a number').nullable().required('General: Seller price is required'),
  year: Yup.string().nullable().required('General: Year is required'),
  make: Yup.object().nullable().required('General: Make is required'),
  model: Yup.object().nullable().required('General: Model is required'),
  generation: Yup.object().nullable().required('General: Generation is required'),
  trim: Yup.object().nullable().required('General: Trim is required'),
  mileage: Yup.number('General: Should be a number').nullable().required('General: Mileage is required'),
  engine: Yup.object().nullable().required('General: Engine options are required'),
  registered_emirates: Yup.string().nullable().required('General: Registered emirates is required'),
  body_type: Yup.string(),
  exterior_color: Yup.string().nullable(),
  interior_color: Yup.string().nullable(),
  interior_type: Yup.string(),
  specification: Yup.string(),
  is_new: Yup.boolean(),
  first_owner: Yup.boolean(),
  keys: Yup.string(),
  service_history: Yup.string(),
  manuals: Yup.string(),
  warranty: Yup.boolean(),
  accident_history: Yup.string(),
  bank_finance: Yup.boolean(),
  car_history_comment: Yup.string(),

  // Documents
  id_images: Yup.array(),
  registeration_card_images: Yup.array(),
  vin_images: Yup.array(),
  insurance_images: Yup.array(),

  // Exterior
  defect: Yup.string().nullable(),
  markers: Yup.array(),

  // Engine
  Radiator_Condition: Yup.string(),
  Silencer: Yup.string(),
  Axels: Yup.string(),
  Engine_Belts: Yup.string(),
  Gear_Lever: Yup.string(),
  Radiator_Fan: Yup.string(),
  Engine_Idling: Yup.string(),
  Engine_Noise: Yup.string(),
  Engine_Oil: Yup.string(),
  Engine_Smoke: Yup.string(),
  Exhaust: Yup.string(),
  Coolant: Yup.string(),
  Battery_Condition: Yup.string(),
  Gear_Shifting: Yup.string(),
  Shift_Interlock_Condition: Yup.string(),
  Chassis: Yup.string(),
  Chassis_Extension: Yup.string(),
  Oil_Leaks: Yup.string(),
  Water_Sladge: Yup.string(),
  Engine_Comment: Yup.string(),
  Warning_Signal: Yup.boolean(),

  // SSA
  Brake_Pads: Yup.string(),
  Brake_Discs_Or_Lining: Yup.string(),
  Parking_Brake_Operations: Yup.string(),
  Suspension: Yup.string(),
  Shock_Absorber_Operation: Yup.string(),
  Steering_Operation: Yup.string(),
  Steering_Alignment: Yup.string(),
  Wheel_Alignment: Yup.string(),
  Steering_Comment: Yup.string(),

  // IEAC
  Dashboard_Condition: Yup.string(),
  Steering_Mounted_Controls: Yup.string(),
  Center_Console_Box: Yup.string(),
  Speedometer_Cluster: Yup.string(),
  Door_Trim_Panels: Yup.string(),
  Headliner: Yup.string(),
  Seat_Controls: Yup.string(),
  Boot_Trunk_Area: Yup.string(),
  Central_Lock_Operation: Yup.string(),
  Music_Multimedia_System: Yup.string(),
  Navigation_Control: Yup.string(),
  Headlights: Yup.string(),
  Tail_Lights: Yup.string(),
  Sunroof_Condition: Yup.string(),
  Windows_Controls_Condition: Yup.string(),
  Cruise_Control: Yup.string(),
  Push_Stop_Button: Yup.string(),
  AC_Cooling: Yup.string(),
  Convertible_Operations: Yup.string(),
  AC_Heating: Yup.string(),
  Airbag: Yup.string(),
  Interior_Comment: Yup.string(),

  // Specs
  Fog_Lights: Yup.boolean(),
  Parking_Sensor: Yup.boolean(),
  Winch: Yup.boolean(),
  Roof_Rack: Yup.boolean(),
  Spoiler: Yup.boolean(),
  Dual_Exhaust: Yup.boolean(),
  Alarm: Yup.boolean(),
  Rear_Video: Yup.boolean(),
  Premium_Sound: Yup.boolean(),
  Heads_Up_Display: Yup.boolean(),
  Aux_Audio: Yup.boolean(),
  Bluetooth: Yup.boolean(),
  Climate_Control: Yup.boolean(),
  Keyless_Entry: Yup.boolean(),
  Keyless_Start: Yup.boolean(),
  Leather_Seats: Yup.boolean(),
  Racing_Seats: Yup.boolean(),
  Cooled_Seats: Yup.boolean(),
  Heated_Seats: Yup.boolean(),
  Power_Seats: Yup.boolean(),
  Power_Locks: Yup.boolean(),
  Power_Mirrors: Yup.boolean(),
  Power_Windows: Yup.boolean(),
  Memory_Seats: Yup.boolean(),  
  View_Camera: Yup.boolean(),
  Blind_Spot_Indicator: Yup.boolean(),
  Anti_Lock: Yup.boolean(),
  Adaptive_Cruise_Control: Yup.boolean(),
  Power_Steering: Yup.boolean(),
  Side_Steps: Yup.boolean(),
  Carbon_Fiber_Interior: Yup.boolean(),
  Line_Change_Assist: Yup.boolean(),
  Park_Assist: Yup.boolean(),
  Adaptive_Suspension: Yup.boolean(),
  Height_Control: Yup.boolean(),
  Navigation_System: Yup.boolean(),
  Drives: Yup.string(),
  Tiptronic_Gears: Yup.string(),
  Sunroof_Type: Yup.string(),
  Wheel_Type: Yup.string(),
  Convertible: Yup.string(),
  Other_Features: Yup.string(),

  // Tyres
  FrontLeft: Yup.string(),
  FrontRight: Yup.string(),
  RearLeft: Yup.string(),
  RearRight: Yup.string(),
  SpareTyre: Yup.boolean(),

  // Images
  images: Yup.array().required('images: Please add at least one image').min(1)
});

export const AllDefaultValues = {
  // General
  seller_id: '',
  seller_price: '',
  year: "",
  make: '',
  model: '',
  generation: '',
  trim: '',
  mileage: 0,
  registered_emirates: "",
  engine: "",
  body_type: "",
  exterior_color: '',
  interior_color: '',
  interior_type: "",
  specification: "",
  is_new: true,
  first_owner: false,
  keys: "",
  service_history: "",
  manuals: "",
  warranty: true,
  accident_history: "",
  bank_finance: false,
  car_history_comment: "",

  // Documents
  id_images: [],
  registeration_card_images: [],
  vin_images: [],
  insurance_images: [],

  // Exterior
  defect: "",
  markers: [],

  // Engine
  Radiator_Condition: 'good',
  Silencer: 'normal',
  Axels: 'good',
  Engine_Belts: 'good',
  Gear_Lever: 'good',
  Radiator_Fan: 'good',
  Engine_Idling: 'normal',
  Engine_Noise: 'normal',
  Engine_Oil: 'good',
  Engine_Smoke: 'normal',
  Exhaust: 'normal',
  Coolant: 'good',
  Battery_Condition: 'good',
  Gear_Shifting: 'good',
  Shift_Interlock_Condition: 'good',
  Chassis: 'good',
  Chassis_Extension : 'good',
  Oil_Leaks: 'none',
  Water_Sladge: 'none',
  Engine_Comment: '',
  Warning_Signal: true,

  // SSA
  Brake_Pads: "good",
  Brake_Discs_Or_Lining: "good",
  Parking_Brake_Operations: "good",
  Suspension: "good",
  Shock_Absorber_Operation: "good",
  Steering_Operation: "good",
  Steering_Alignment: "good",
  Wheel_Alignment: "good",
  Steering_Comment: "",

  // IEAC
  Dashboard_Condition: "good",
  Steering_Mounted_Controls: "good",
  Center_Console_Box: "good",
  Speedometer_Cluster: "good",
  Door_Trim_Panels: "good",
  Headliner: "good",
  Seat_Controls: "good",
  Boot_Trunk_Area: "good",
  Central_Lock_Operation: "good",
  Music_Multimedia_System: "good",
  Navigation_Control: "good",
  Headlights: "good",
  Tail_Lights: "good",
  Sunroof_Condition: "good",
  Windows_Controls_Condition: "good",
  Cruise_Control: "average",
  Push_Stop_Button: "good",
  AC_Cooling: "good",
  Convertible_Operations: "good",
  AC_Heating: "good",
  Airbag: "good",
  Interior_Comment: "",

  // Specs
  Fog_Lights: true,
  Parking_Sensor: true,
  Winch: true,
  Roof_Rack: true,
  Spoiler: true,
  Dual_Exhaust: true,
  Alarm: true,
  Rear_Video: true,
  Premium_Sound: true,
  Heads_Up_Display: true,
  Aux_Audio: true,
  Bluetooth: true,
  Climate_Control: true,
  Keyless_Entry: true,
  Keyless_Start: true,
  Leather_Seats: true,
  Racing_Seats: true,
  Cooled_Seats: true,
  Heated_Seats: true,
  Power_Seats: true,
  Power_Locks: true,
  Power_Mirrors: true,
  Power_Windows: true,
  Memory_Seats: true,
  View_Camera: true,
  Blind_Spot_Indicator: true,
  Anti_Lock: true,
  Adaptive_Cruise_Control: true,
  Power_Steering: true,
  Side_Steps: true,
  Carbon_Fiber_Interior: true,
  Line_Change_Assist: true,
  Park_Assist: true,
  Adaptive_Suspension: true,
  Height_Control: true,
  Navigation_System: true,
  Drives: 'good',
  Tiptronic_Gears: 'working',
  Convertible: 'hard_top',
  Sunroof_Type: 'sunroof',
  Wheel_Type: '2wd',

  Other_Features: '',

  // Tyres
  FrontLeft: "",
  FrontRight: "",
  RearLeft: "",
  RearRight: "",
  Spare_Tyre: false,

  // Images
  images: [],
};
